Repository LikeLion-2team/readers, pull requests merged in 2023-11, with the labels that each got.

#11 Featur/#6 유저 회원가입 / 로그인 기능
  src/main/java/com/project/readers/controller/UserController.java
  src/main/java/com/project/readers/entity/UserDTO.java
  src/main/java/com/project/readers/entity/UserSessionDTO.java
  src/main/java/com/project/readers/repository/UserDAO.java
  src/main/java/com/project/readers/service/UserService.java
  src/main/resources/mapper/UserMapper.xml
  src/main/resources/templates/login.html
  src/main/resources/templates/register.html
Labels: enhancement

#14 [FEAT] 게시판 기능 구현
  .gitignore
  src/main/java/com/project/readers/config/SessionConfig.java
  src/main/java/com/project/readers/controller/BoardController.java
  src/main/java/com/project/readers/controller/ReplyController.java
  src/main/java/com/project/readers/entity/BoardDTO.java
  src/main/java/com/project/readers/entity/ReplyDTO.java
  src/main/java/com/project/readers/repository/BoardDAO.java
  src/main/java/com/project/readers/repository/ReplyDAO.java
  src/main/java/com/project/readers/service/BoardService.java
  src/main/java/com/project/readers/service/ReplyService.java
  src/main/resources/mapper/BoardMapper.xml
  src/main/resources/mapper/ReplyMapper.xml
Labels: enhancement

#20 최종 설정 및 수정
  src/main/java/com/project/readers/common/Constant.java
  src/main/java/com/project/readers/common/interceptor/AdminCheckInterceptor.java
  src/main/java/com/project/readers/common/interceptor/GuestCheckInterceptor.java
  src/main/java/com/project/readers/common/interceptor/UserCheckInterceptor.java
  src/main/java/com/project/readers/config/IPconfig.java
  src/main/java/com/project/readers/config/SessionConfig.java
  src/main/java/com/project/readers/config/UserRoleConfig.java
  src/main/java/com/project/readers/config/WebConfig.java
  src/main/java/com/project/readers/controller/MainController.java
  src/main/java/com/project/readers/controller/UserController.java
  src/main/java/com/project/readers/repository/MainDAO.java
  src/main/java/com/project/readers/service/ChatRoomService.java
  src/main/java/com/project/readers/service/MainService.java
  src/main/resources/mapper/MainMapper.xml
  src/main/resources/templates/assets/css/sideBar.css
  src/main/resources/templates/assets/css/styles.css
  src/main/resources/templates/chat.html
  src/main/resources/templates/html/index.html
  src/main/resources/templates/login.html
Labels: documentation, enhancement

#23 [FEAT] 게시글 화면 구현
  build.gradle
  src/main/java/com/project/readers/controller/BoardController.java
  src/main/java/com/project/readers/controller/BoardCotroller.java
  src/main/java/com/project/readers/controller/ReplyController.java
  src/main/java/com/project/readers/service/BoardService.java
  src/main/java/com/project/readers/service/ReplyService.java
  src/main/resources/static/js/board.js
  src/main/resources/static/js/reply.js
  src/main/resources/templates/board/board_list.html
  src/main/resources/templates/board/board_update.html
  src/main/resources/templates/board/board_write.html
Labels: enhancement

#24 Feature/#22
  src/main/java/com/project/readers/controller/MainController.java
  src/main/resources/mapper/MainMapper.xml
  src/main/resources/static/js/app.js
  src/main/resources/templates/chat.html
  src/main/resources/templates/html/authentication-login.html
  src/main/resources/templates/html/authentication-register.html
  src/main/resources/templates/html/icon-tabler.html
  src/main/resources/templates/html/index.html
  src/main/resources/templates/html/index1.html
  src/main/resources/templates/html/sample-page.html
  src/main/resources/templates/html/test.html
  src/main/resources/templates/html/ui-alerts.html
  src/main/resources/templates/html/ui-buttons.html
  src/main/resources/templates/html/ui-card.html
  src/main/resources/templates/html/ui-forms.html
  src/main/resources/templates/html/ui-typography.html
  src/main/resources/templates/layout/nav.html
Labels: enhancement

#26 Feature#26/total config
  src/main/java/com/project/readers/common/interceptor/AdminCheckInterceptor.java
  src/main/java/com/project/readers/common/interceptor/UserCheckInterceptor.java
  src/main/java/com/project/readers/config/WebConfig.java
  src/main/java/com/project/readers/repository/MainDAO.java
  src/main/java/com/project/readers/service/MainService.java
  src/main/resources/application.properties
  src/main/resources/mapper/MainMapper.xml
Labels: bug, documentation, enhancement

#30 Feature/#29 total
  build.gradle
  src/main/java/com/project/readers/common/Constant.java
  src/main/java/com/project/readers/common/interceptor/AdminCheckInterceptor.java
  src/main/java/com/project/readers/common/interceptor/UserCheckInterceptor.java
  src/main/java/com/project/readers/config/SessionConfig.java
  src/main/java/com/project/readers/controller/ChatRoomController.java
  src/main/java/com/project/readers/controller/MainController.java
  src/main/java/com/project/readers/entity/ChatMesgDTO.java
  src/main/java/com/project/readers/entity/ChatRoomDTO.java
  src/main/java/com/project/readers/repository/MainDAO.java
  src/main/java/com/project/readers/service/ChatRoomService.java
  src/main/java/com/project/readers/service/MainService.java
  src/main/resources/mapper/ChatMesgMapper.xml
  src/main/resources/mapper/MainMapper.xml
  src/main/resources/static/js/app.js
  src/main/resources/templates/chat.html
  src/main/resources/templates/html/ui-card.html
  src/main/resources/templates/login.html
Labels: documentation

#33 Feature/#32 chart
  src/main/java/com/project/readers/common/interceptor/AdminCheckInterceptor.java
  src/main/java/com/project/readers/common/interceptor/UserCheckInterceptor.java
  src/main/java/com/project/readers/controller/MainController.java
  src/main/java/com/project/readers/service/MainService.java
  src/main/resources/templates/html/ui-card.html
Labels: documentation

#35 getday 디버그
  src/main/java/com/project/readers/service/MainService.java
  src/main/resources/mapper/MainMapper.xml
Labels: documentation

#42 [FEAT] 게시판 화면과 댓글 화면 구현
  src/main/java/com/project/readers/controller/BoardController.java
  src/main/java/com/project/readers/controller/ReplyController.java
  src/main/java/com/project/readers/service/ReplyService.java
  src/main/resources/static/js/reply.js
  src/main/resources/templates/board/board_list.html
  src/main/resources/templates/board/board_update.html
  src/main/resources/templates/board/board_write.html
  src/main/resources/templates/html/ui-card.html
  src/main/resources/templates/layout/nav.html
Labels: enhancement
